version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
